#!/usr/bin/env python
""" ggservice -- ggsci RESTful query service """

#------------------------------------------------------------------------
import flask, subprocess, json

GGSCI = '/ggate/ggsci'
app = flask.Flask(__name__)

#------------------------------------------------------------------------
@app.route('/infoall')
def infoall():
    x = subprocess.Popen(GGSCI, close_fds=True,
                           stdin=subprocess.PIPE, stdout=subprocess.PIPE)
    x.stdin.write('info all\n')
    result = x.communicate()
    lines = result[0].split('\n')
    rv = []
    for line in lines:
        a = line.split()
        if len(a) > 0:
            kname = a[0]
            if   kname in ['MANAGER','JAGENT']:
                    # Status
                    rv.append([kname, a[1]])
            if kname in ['REPLICAT','EXTRACT']:
                    # Status,Group,Lag at Chkpt,Time Since Chkpt
                    rv.append([kname, a[1:5]])
    return json.dumps(rv, separators=(',',':')) + '\n'

#------------------------------------------------------------------------
if __name__ == '__main__':
    app.debug = True
    app.run()
